### ISSUE TITLE
Create a ListView and a DetailView

### ISSUE THREAD

**Issue by khchine5** [openhealthcare/opal#1003]
Hi all,
I am trying to understand Opal in deep , so I am working to implement a training Opal plugin. So far I found very interesting  technical features (bootstrapping ..). But there is some points still not clear how to do with Opal.

- How can I show a list of items of a EpisodeSubrecord or PatientSubrecord (thus Demographics) for all patients.
- Then how can I edit any item of that list using a similar way as done with Demographics as an example but without using a popup features.

I have been able to do a working example of the first point. But it is not very elegant and clear.

Thanks folks.

**Comment by davidmiller** [comment]
Hi @khchine5 !

There's not a _super_ easy answer to these, and it's hard without seeing your code or understanding your use case - but let me do my best: 

## Lists of subrecords

For lists of things, I would naturally use a `PatientList` and customise the display template. We almost always do this in the context of iterating over `Episodes` - even if we display little data, or phrase it differently in the UI :)

So something like the custom list views here perhaps:
List:
https://github.com/odonto/odonto-rms/blob/master/rms/patient_lists.py#L50
Template: 
https://github.com/odonto/odonto-rms/blob/master/rms/templates/referral_table_list.html

If you wanted literally all patients, you'd change the queryset to return all episodes...

## Editing detail views

I'm afraid it's not really very clear what your real use case is here :( 

If you're talking about wanting a detail view for one particular instance of a subrecord (much like e.g. the Django Admin edit page), then honestly we very rarely see good use cases for that, but you could do it with something like this:
https://gist.github.com/davidmiller/3ed8618b415e342a181376ab8973c18d

More regularly we see use cases where either we want to edit or add a subrecord 'inline' inside a detail page, or another arbitrary page. We tend to use custom local controllers with Angular "controller as" syntax. @fredkingham is probably more expert than me at these and could point you at some examples.

## The Pathway Plugin

More generally, most of the forms-related work we do with Opal these days lives inside [Opal Pathway](http://github.com/openhealthcare/opal-pathway) - which caters for plenty of cases more advanced than simply 'edit one thing in a modal'.

The Pathway plugin is approaching the level of maturity and completeness where we are starting to think about how to move it into Opal itself.

Things that we might do with Pathway include something like "put all instances of a drug connected to this episode into a series of inline forms and then allow the user to edit all of them at once without being in a modal" :

![screen shot 2017-03-06 at 13 27 24](https://cloud.githubusercontent.com/assets/17229/23611799/ae9d44c8-0270-11e7-85dc-4ef927f81e55.png)
(Screenshot from https://github.com/openhealthcare/uclp-tb)

Again, @fredkingham is the Pathway expert in residence and I'm sure can answer any questions better than me !

Hope this helps - are these the kinds of things you mean?
(If not, let's figure out your use case in more detail !)

If your plugin code was on Github I suspect we'd be able to give more specific advice to your situation ;)

**Comment by khchine5** [comment]
Thanks very much @davidmiller for your response. I know it is a complicated question.

I am just pushed my base code for my plugin to GitLab ( sorry to switch to gitlab rather than here on Github). My plugin is just an experimental one to try to play with Opal and use in use case.
My plugin code is here https://gitlab.com/khchine5/opal-kinepro

Please forgive me whenever you found a stupid code.

I will try your propositions with my code and also the Pathway which I guess would help a lot.

**Comment by davidmiller** [comment]
Hi @khchine5 - thanks for adding your code to Gitlab !

I totally understand the process of playing with code to understand a new tool or framework - no need to apologise for the code - this is how I learn new things too :) 

I _think_ I understand what you're doing - you want a page at `/kinepro/#/pec` that lists all the instances of `PECItem` and then a page at `/kinepro/#/pec/1` that allows you to edit e.g. the `PECItem` with id=1 ?

This is pretty interesting to us...
Honestly we rarely write applications where you would have a list of subrecords across different patients/episodes without including the patient details, and rarely have a whole page edit form that is dealing with a single instance of a subrecord. Because of this the thing you're trying to do is possibly a little harder than it could be.

(That's great - it gives us a good opportunity to see if we can make this use case easier ! )
Perhaps I don't really understand what a PECItem is - it seems a bit like a TODO list item?

I had a little play, and I think this patch (https://gist.github.com/davidmiller/d66a6dad8fc2aa3329eb54831294e000) should get you closer to what you want. You should be able to apply it with e.g. `git apply suggestion.patch`

Couple of notes:

In general with Opal applications we tend not to put too much instance data into templates on the server side. Instead we call the JSON APIs at `http://localhost:8000/api/v0.1/` and render the data with Angular.

You could render the same data with Django templates and using e.g. Django forms, but mixing the two creates lots of problems because of cached templates not updating, and data injected on the server not being updated when Angular updates something. 

We almost never work with Subrecords on the client side without an Episode - although this code works, there are some gotchas because `new Item()` expects an episode which you don't have in the `pec.js`.

I would probably update the app so that the edit/detail page was working with an episode - changing the URL to perhaps `/pec/:episode_id/:pec_id`... 

That way you can load the Episode data via the `episodeLoader` service (and you don't have to call `recordLoader` yourself) and your detail template has extra useful context to work with. For instance - if a PECItem is like a job to be done, you can include something like the name of the patient, the location of the patient in the template because you've loaded the data. That helps to make users comfortable they are editing the right thing!

Hope that helps - let me know if it doesn't make sense or I'm not understanding your use case properly :)

**Comment by davidmiller** [comment]
@fredkingham see above - I think we might consider implementing a `list()` method for `opal.core.api.SubrecordViewSet`...

Would only make sense if we could make `Item()` cope gracefully with not having an episode instance.
I _think_ that's probably sensible?

You would throw an error for tagging because it's not a 'real' subrecord, throw an error, for POST requests (because you don't know what to associate a new subrecord instance with unless you have that) and destroy() could skip the `Episode.removeItem()` call ?

**Comment by khchine5** [comment]
Hi @davidmiller , 
Thanks for you explanation and your patch. I am going to try it.

**Comment by khchine5** [comment]
@davidmiller ,I had just send an e-mail to david at openhealthcare.org.uk for a working use case.
Thanks for your effort.

**Comment by davidmiller** [comment]
Thanks - glad to have helped ! 

(I'm going to close this issue here for now I think - if we proceed with the suggestions above those are separate PRs/issues)
