### ISSUE TITLE
default start project points at opal 0.9.0 but that doesn't exist!

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#1269]

**Comment by davidmiller** [comment]
I think we did that deliberately to set the scaffold opal requirement to be whatever version you used to run startproject.
(https://github.com/openhealthcare/opal/commit/adef79f66de1fa89b03fa86acd2bf0aa851ea620)

The expectation is that you'll be doing that from a PyPi release and so that will make your e.g. Heroku instance pull the same version as the one you're running with locally. 

AFAICT this is only an issue if you're running the current development branch which doesn't yet have a release...
