### ISSUE TITLE
Feature: allowing patients to decide who can access their medical record details

### ISSUE THREAD

**Issue by surawinfo** [openhealthcare/opal#1291]
I am new to opal, and going through the documentation for a while. To make my life a bit easy, is there any suggested way to start off developing a "clinical service" that can allow clients/patients to control who can be seen and what to share from their medical records? 

Thanks a lot!

**Comment by fredkingham** [comment]
hi @surawinfo I think that sounds possible. It not a requirement we've ever had and it's a bit difficult to say without knowing the details. 

I think if you added in an abstract django model mixin that said 'private' probably with a boolean to start with then scaffold up all your forms.

You need an understanding of roles, ie the User would be a Patient, Doctor etc. That could be done with django models or Opal's [UserProfile](http://opal.openhealthcare.org.uk/docs/reference/user_profile_model/) model. 

You then need to change the record panel template to filter based on the role. Does that help?

**Comment by davidmiller** [comment]
Hi ! 

As Fred says, it's not something we've ever implemented so there isn't an established pattern, but it's an interesting thing to look at. Lots depends on exactly the sharing model you'd be going for, but I imagine you could get a proof of concept to iterate on fairly quickly...
(This is a simplistic sharing model that would give you a basis to work from that ignores signup flow... I assume your actual requirements would be more complex)

- Create a model to link patients and users (For now we assume that this magically gets populated appropriately - in reality I expect the workflow around that would be complex and subtle)
- Create a 'patient' and 'clinician' role in your application (https://github.com/openhealthcare/opal/blob/v0.9.0/opal/models.py#L1577)
- Make sure that patient and clinician users have the correct role linked in their Profile (https://github.com/openhealthcare/opal/blob/v0.9.0/opal/models.py#L1606)
- Create a controller that redirects patients to their own record rather than a search interface for all records (https://github.com/openhealthcare/opal/blob/v0.9.0/opal/scaffolding/scaffold/app/static/js/app/routes.js#L11) 
- Alter e.g. menu items to display only with the correct roles by overriding `Application.get_menu_items` (http://opal.openhealthcare.org.uk/docs/v0.9.0/reference/opal_application/#opalapplicationget_menu_itemsusernone) 
- Add fields to the scaffolded clinical models that wind up in your app's `models.py` from https://github.com/openhealthcare/opal/blob/v0.9.0/opal/scaffolding/scaffold/app/models.py.jinja2  something like `share = models.BooleanField(default=???)` 
- Override the forms for each subrecord (http://opal.openhealthcare.org.uk/docs/v0.9.0/guides/forms/#form-and-modal-templates) so that patients see a 'share' button  (In the form template you have access to an angular variable `profile` which has the helper method `profile.has_role('patient')` which allows you to show hide based on role
- Override the display templates to show / hide based on e.g. `profile.has_role('clinician')` and `item.share` 

After that you can get into something with finer grained permissions...

HTH!

**Comment by surawinfo** [comment]
Hi @fredkingham  @davidmiller 

Thank you so much! for the details, these helps to get to work. I will see what I can do and get back to this post again.

**Comment by davidmiller** [comment]
Hi @surawinfo hopefully this was helpful, and best of luck - I'm going to close this as an open issue, but do feel free to get in touch if you have further questions - either here or on the mailing list!
