### ISSUE TITLE
ImportError: No module named grp

### ISSUE THREAD

**Issue by andymac44** [openhealthcare/opal#1297]
Hi - I've installed opal on windows (server 2012). However when I run it I get "ImportError: No module named grp" . I believe grp is a Linux/unix groups module. Does this imply that opal doesn't run on windows ?

thanks

Andy

**Comment by davidmiller** [comment]
Hi @andymac44 ! 

Sorry for the delay in getting back to you.

This is something we know about - although Opal used to run on Windows, we've thus far been unable to actively support it. (See conversation https://github.com/openhealthcare/opal/issues/918)

However it looks like we're very close to agreeing some funding to fix the various upstream bugs and get everything running on Windows again. After that we'll be adding it into our CI setup so that any new code will at least be made to run without erroring on Windows, which should help lots !

**Comment by andymac44** [comment]
thanks David. I'll look at using Linux for now and then got back to windows when it's ready.

**Comment by lamby** [comment]
This was fixed in https://github.com/davidmiller/ffs/pull/14
