### ISSUE TITLE
default bootstrap offset for checkboxes causes formatting issues in dense checkbox formations

### ISSUE THREAD

**Issue by pacharanero** [openhealthcare/opal#1414]
![image](https://user-images.githubusercontent.com/2348385/36485402-0bff5efe-1714-11e8-9134-2ea71d581d33.png)

It causes large amounts of unused space that we don't have control over

![image](https://user-images.githubusercontent.com/2348385/36485556-6d0a3232-1714-11e8-8598-174a88dbf510.png)

(the above is a standard Bootstrap `row` with 3 columns of `col-md-4` each)

Is there a way around this eg overriding templates that come from Opal?

**Comment by davidmiller** [comment]
The indentation and whitespace is set like this so that they are aligned with the other form widgets in a bootstrap `form-horizontal` style.

Yes there is a template you can override... (`./opal/templates/_helpers/checkbox.html`)

...but in this particular case, you might like to try passing in the argument `style="vertical"` to the `checkbox` templatetag.

Your application's css can also of course just apply whatever css rules you feel like.

Further down the line as an enhancement we might like to make these form widget templates more obviously extensible e.g. provide hooks with good `{% block x %}` design rather than asking people to override wholesale - the logic of those form templatetags is a bit involved at times. 

Probably at the same time we move them out of the `_helpers` path and into `templatetags/forms`.
