### ISSUE TITLE
Accessing Patient from Pathway Scope: Refactor / enhancement

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal#1433]
If I have a pathway with which I'm intending to create a new episode for an existing patient, I have no way of accessing the Patient details on the front end without ??? implementing my own custom Pathway Service ???.

I believe the resolver in the pathway app route that passes you to `PathwayCtrl` should fetch Patient rather than episode, and then by all means, if an episode ID is specified then let's pluck that one off the patient and populate scope accordingly, but this would enable me to see patient subrecords / demographics at `/pathway/#/mine/343/` without needing to do anything "clever"...

**Comment by fredkingham** [comment]
Yeah, its a good call.

The reason why its episode based is because we do item.makeCopy "stuff" and Item requires an episode.

I think we need to change this.

Other background information/things to think about.

I'm not sure how this is all going to work with the RFH serialise a bit of an episode.

In theory if you're getting from /my_pathway/1

you'd expect to get the serialised patient

if you're getting from /my_pathway/1/2

you'd expect to get the serialised episode

if you're getting from /my_lab_numbers/112322

Do you expect everything?

The other side of this is the other side of the api.

myStepController(scope, data, episode).

At the moment episode is there for two reasons.

1. this is what we started with, ie its the before snap shot (if for some reason you wanted one)

2. this is how we create new items. That was for the old implementation of the add many step before the directive.

**Comment by davidmiller** [comment]
If you're defining your own URLparams then I think you expect to be in control of what you're getting back, at least short term.

We might like to think of it as closer to the output of `.get_context_data()`. Might not...

I don't particularly follow the issue with makeCopy/items... I'm suggesting we pull from `patientLoader` - which will give us plenty of `Patient` and `Episode` instances to work with...

**Comment by davidmiller** [comment]
Having thought more about this, I suspect we want a more far-reaching version of this that moves the URLs completely out of Angular...  Closing this now - I suspect we're unlikely to deal with this particular refactor any time soon
