### ISSUE TITLE
Idea: Opal 'Stories' for testing might be automatable using pyautogui

### ISSUE THREAD

**Issue by pacharanero** [openhealthcare/opal#1518]
This cross-platform python package can find UI elements (by matching a screenshot of them) wherever they are in the screen, using OpenCV, and has an API which allows interaction (click, typing, etc) with these elements.

This is different to using Seleniuim or PhantomJS where you are reliant on knowing the screen dimensions and co-ordinates of the elements, or traversing the DOM.

https://github.com/asweigart/pyautogui

A human operator would still need to verify success or failure of the Story.

**Comment by davidmiller** [comment]
If we were going to write that kind of integration testing, I'd rather have selenium and traverse the DOM.

I think CV is black magic and witches should be burned.*

I'm not against doing integration tests, we've just not yet. They'd go in a couple of applications, then we'd figure out what the common tools / framework / etc should look like and add that to Opal.

Honestly I think having the human operator click the buttons and do the typing for stories is a _good_ thing and an important part of the process...

It means that somebody from _our team_ has to "use" the application on a frequent basis. This is important because we can't _actually_ use the application.

* I do not think these things.

**Comment by fredkingham** [comment]
I essentially agree with David, I think stories are necessary. 

Automated boolean tests are all well and good but they don't tell you when you've changed the background to a lovely shade of electric pink.

**Comment by davidmiller** [comment]
I'm closing this - automated integration testing of this nature isn't on a short-medium term roadmap and could be implemented by a plugin without needing anything in Opal itself.
