### ISSUE TITLE
ImportError: cannot import name 'OrderedDict'

### ISSUE THREAD

**Issue by ImperialIain** [openhealthcare/opal#1566]
Environment: python 3.5, pipenv 11.6.1
To reproduce:
```
pipenv python 3
pipenv install opal
pipenv shell
opal startproject mynewapp
[error here, see below]
^C
python manage.py makemigrations
[error here, see below]
```

Hi,

I installed opal using pipenv.  From pipenv-shell I ran "opal startproject mynewapp" but got a Celery error:

> File "/home/iain/.local/share/virtualenvs/opal-ua5MY8wK/lib/python3.5/site-packages/celery/five.py", line 153, in <module>
>     from kombu.utils.compat import OrderedDict  # noqa
> ImportError: cannot import name 'OrderedDict'

Updating celery seems to fix it:
pipenv install celery==4.1

but results in a warning from pipenv that celery 3.1.25 is required:

> Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.

I don't know whether you could require celery >= 4.0 instead?

This is how the pipenv dependency graph appears

> anyjson==0.3.3
> django-ipware==2.1.0
> opal==0.11.0
>   - celery [required: ==3.1.25, installed: 4.1.0]
>     - billiard [required: <3.6.0,>=3.5.0.2, installed: 3.5.0.3]
>     - kombu [required: >=4.0.2,<5.0, installed: 4.2.1]
>       - amqp [required: <3.0,>=2.1.4, installed: 2.3.2]
>         - vine [required: >=1.1.3, installed: 1.1.4]
>     - pytz [required: >dev, installed: 2018.5]
>   - django [required: ==1.10.8, installed: 1.10.8]
>   - django-axes [required: ==1.7.0, installed: 1.7.0]
>   - django-celery [required: ==3.2.2, installed: 3.2.2]
>     - celery [required: <4.0,>=3.1.15, installed: 4.1.0]
>       - billiard [required: <3.6.0,>=3.5.0.2, installed: 3.5.0.3]
>       - kombu [required: >=4.0.2,<5.0, installed: 4.2.1]
>         - amqp [required: <3.0,>=2.1.4, installed: 2.3.2]
>           - vine [required: >=1.1.3, installed: 1.1.4]
>       - pytz [required: >dev, installed: 2018.5]
>     - django [required: >=1.8, installed: 1.10.8]
>   - django-compressor [required: ==2.2, installed: 2.2]
>     - django-appconf [required: >=1.0, installed: 1.0.2]
>     - rcssmin [required: ==1.0.6, installed: 1.0.6]
>     - rjsmin [required: ==1.0.12, installed: 1.0.12]
>   - django-reversion [required: ==1.10.2, installed: 1.10.2]
>     - django [required: >=1.8, installed: 1.10.8]
>   - djangorestframework [required: ==3.4.7, installed: 3.4.7]
>   - ffs [required: >=0.0.8.2, installed: 0.0.8.2]
>     - six [required: >=1.2.0, installed: 1.11.0]
>   - jinja2 [required: ==2.10, installed: 2.10]
>     - MarkupSafe [required: >=0.23, installed: 1.0]
>   - letter [required: ==0.4.1, installed: 0.4.1]
>     - ffs [required: >=0.0.7, installed: 0.0.8.2]
>       - six [required: >=1.2.0, installed: 1.11.0]
>     - jinja2 [required: Any, installed: 2.10]
>       - MarkupSafe [required: >=0.23, installed: 1.0]
>   - python-dateutil [required: ==2.4.2, installed: 2.4.2]
>     - six [required: >=1.5, installed: 1.11.0]
>   - requests [required: ==2.18.4, installed: 2.18.4]
>     - certifi [required: >=2017.4.17, installed: 2018.4.16]
>     - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
>     - idna [required: <2.7,>=2.5, installed: 2.7]
>     - urllib3 [required: <1.23,>=1.21.1, installed: 1.23]
>   - six [required: >=1.10.0, installed: 1.11.0]

**Comment by davidmiller** [comment]
Afternoon @ImperialIain 

That's interesting - we're yet to really transition to pipenv, so I'm not massively surprised that this has happened.

(In fact [something similar](https://github.com/openhealthcare/opal/pull/1399) was happening a few months ago)

Immediately, virtualenv[wrapper] based workflows should continue to work.

WRT actually fixing this, it happened here: 
https://github.com/openhealthcare/opal/commit/71fad61994fca2ead6044678ab23964efcc88337

As a minimum we should really test these with pipenv when bumping dependency versions - it's not like we do that all the time...
Otherwise an integration-ish test in the CI wouldn't go amiss.

Questions: Is there an interim way to tell pipenv to just let me use the current dependencies even if it thinks it knows better? 
Or to tell it to live with these mismatches? 

We can likely upgrade Celery, though we'll need to take the time to work through the changelogs...

**Comment by davidmiller** [comment]
Closing after a quiet > 6months
