### ISSUE TITLE
Opal Installation and startproject in linux

### ISSUE THREAD

**Issue by arabin-android** [openhealthcare/opal#1705]
Hello 
I tried to install opal in ubuntu 16.04 where python default version is 2.7.13. Found the following error during _installation. 
<img width="733" alt="Screen Shot 2019-04-04 at 10 35 26 AM" src="https://user-images.githubusercontent.com/7425616/55564712-80725280-56c6-11e9-8a31-fcee7d632cbc.png">

Then i installed python3.7.3 and set it as default. After that when tried to start a new project got the following error. Can anyone help me with these issues?

<img width="735" alt="Screen Shot 2019-04-04 at 10 37 48 AM" src="https://user-images.githubusercontent.com/7425616/55564800-b44d7800-56c6-11e9-9f05-c05fdace5457.png">

**Comment by pacheco7** [comment]
Hi.

I got the same error in using python 2.7.6. I'm using Ubuntu 19.04.

**Comment by fredkingham** [comment]
Hi guys opal requires python 3.4 or above. 

My suggestion would be to install python3 for @pacheco7 that's quite easy, a bit trickier on ubuntu 16.04

https://docs.python-guide.org/starting/install3/linux/

**Comment by davidmiller** [comment]
Based on the traceback above this looks very much like it's an issue with Python environment and version management rather than a bug with our installation or startproject - I'm going to close this ticket. Feel free to post the mailing list if you're still struggling to get a new project up and running.
