### ISSUE TITLE
I can't find welcome.html in templates/ folder

### ISSUE THREAD

**Issue by luca400** [openhealthcare/opal#1894]
I can't find welcome.html in templates folder. How can I change the style of the home page

**Comment by davidmiller** [comment]
Hi @luca400 we don't normally place templates from Opal in the application scaffold so that we can change them in the framework without you having to review every template when you upgrade.

If you want to override a template from opal, you can find the welcome.html template here: https://github.com/openhealthcare/opal/blob/v0.18.4/opal/templates/welcome.html

I'd put that template in your application's templates directory.

**Comment by luca400** [comment]
> Hi @luca400 we don't normally place templates from Opal in the application scaffold so that we can change them in the framework without you having to review every template when you upgrade.
> 
> If you want to override a template from opal, you can find the welcome.html template here: https://github.com/openhealthcare/opal/blob/v0.18.4/opal/templates/welcome.html
> 
> I'd put that template in your application's templates directory.

Thank you very much
