### ISSUE TITLE
stale csrf token

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#596]
can we fix it so that if you haven't logged in for a while it doesn't give you the csrf issue

**Comment by davidmiller** [comment]
@fredkingham do I remember you telling me you know what causes this / how to fix it ?

**Comment by fredkingham** [comment]
To reproduce. 
* Open 2 browser windows
* Both on the opal log in screen
* log in to one
* try and log in to the other
* the second screen will raise a CSRF Exception

**Comment by ghickman** [comment]
It seems that is working as expected in Django land since they rotate the CSRF token after a login.  The error throw in dev lists various reasons for seeing the page, including:

> The form has a valid CSRF token. After logging in in another browser tab or hitting the back button after a login, you may need to reload the page with the form, because the token is rotated after a login.

However this is hardly ideal.

It's possible to customise the view that shows the error page (in dev, I think it's just blank when not using DEBUG) using the [`CSRF_FAILURE_VIEW`](https://docs.djangoproject.com/en/2.0/ref/settings/#csrf-failure-view) setting.  I propose we use that to attempt to redirect the user to the view they were trying to get to originally.  We can make use of the `next` query param and fall back to `/` if that isn't set.  Django's standard auth machinery will catch the case where a user still hasn't authenticated and redirect them back to the login view.

How does that sound?
