### ISSUE TITLE
Install Instructions Fail for Windows 7 under virtualenv

### ISSUE THREAD

**Issue by gdvallance** [openhealthcare/opal#918]
I have attempted to install OPAL according to the instructions at: http://opal.openhealthcare.org.uk/docs/installation/ under a virtualenv environment called `virtualenv` created via Pycharm Professional. 

I have confirmed that I have both `Python` and `pip`. Specifically, versions: 2.7.12 and 9.0.1 respectively within the virtualenv (after upgrading the packages to the latest).

Under the virtualenv I executed: 
`(virtualenv) C:\ ... > pip install opal`  [The ... represents the path to the project under virtualenv.]

The command appeared to execute correctly. And the requisite packages *appear* to be there. However, when I execute: 
`(virtualenv) C:\ ... > opal --version` OR 
`(virtualenv) C:\ ... > opal` 

I get the following error:
`'opal' is not recognised as an internal or external command, operable program or batch file.`

I am a Python novice so any help would be appreciated in getting this sorted. What am I doing wrong?

**Comment by davidmiller** [comment]
Hi @gdvallance !

The short answer is: 

We don't currently provide Windows support for Opal.

If you wanted to immediately try out Opal your best bet is to do so on a Unix environment - otherwise you'll need to work through some issues - sorry :(

More than happy to try and help with that process and debug error messages / offer general Python & Opal advice etc etc either here, on the mailing list or wherever. However we don't really have the skills, knowledge or bandwidth to take on full Windows support (nobody in the office has done programming on windows for many years I'm afraid !).

Specifically looking at the error message you're getting, it seems that somehow either the Opal commandline script isn't being installed by `setup.py` or it's being put somewhere that isn't on your `PATH`...

I'd try looking at what packages are installed in the current python environment you're using by running

```
pip freeze
```
(In fact I'd do `pip freeze | grep opal` to filter the output - but I have no idea how to do that on Windows - this is how basic my lack of understanding of the Windows environment is ! )

We'd be delighted to merge PRs/patches that make it do so and/or work with a Windows maintainer going forwards if you had time/inclination...

**Comment by gdvallance** [comment]
Thanks David. Given you are targetting the NHS it is *interesting* that you don't support Windows :-P Given my druthers I am entirely with you ...

I want to test OPAL as a possible solution for a Departmental (Clinical Haematology) project. Unfortunately, ideally I need to get it working on Windows ... So yes, I am onboard with helping, at least for as long as I am evaluating/using OPAL. 

I don't have time now to do some debugging but I will be back ... 

So let's get it working. Happy to document and indeed anything I learn/do as part of the evaluation.

**Comment by JMathiszig-Lee** [comment]
Hi @gdvallance I use OPAL for a project on my windows machines. You can use a virtual machine (virtualbox with a linux distro of your choice, i like fedora) though that uses a decent chunk of disk space or my preferred option which is windows subsystem for linux which gives you a bash shell running natively in windows and is a more more elegant solution imo. 

To install it type **"turn windows features on and off"** into search and click the application that comes up. You can select the enable the subsystem for linux from here and you'll have to restart your pc for it to take effect. 

Open up command prompt by typing **“cmd”** into the search bar and the use the command “bash” to install, follow the commands to set up a unix username and password that you’ll use within the shell. 
Once this is done search for and open **“bash”**.

Ta! Da! You now have a fully functioning shell on your windows machine. Installing and running opal from here will let you open up the browser within your windows environment to view it rather than within the virtual machine if you did it that way. 

The path to windows files from within the shell is **/mnt/c..... e.g. /mnt/c/Users/username/Documents**
Since you mentioned you’re a novice i’ll make a few more suggestions to get you up and running.
Python is already installed so run 
`
sudo apt-get install python-pip`

For virtual enviroments i’d suggest using virtualenvwrapper (which opal’s ignore file is setup to work with)
`sudo pip install virtualenvwrapper`
We need to edit a file to get the most of it though so snce that’s installed run
`sudo nano ~/.bashrc`
add the following to the end of the file (scroll down with your arrow keys)
```
#forvirtualenvwrapper
export WORKON_HOME=/mnt/c/Users/*yourusername*/Documents/GitHub/.virtualenvs
export PROJECT_HOME=/mnt/c/Users/*yourusername*/Documents/GitHub/
source /usr/local/bin/virtualenvwrapper.sh
```
Use **Control+X** to exit and press **Y** when prompted to save.

Now whenever you want to start a new project use the command 
`mkproject projectname`
and virtualenvwrapper will make a folder and virtual environment in the directory you specificied above. Whenever you want to work on that project use the command
`workon projectname`
and you’ll automatically be taken to that directory and the virtualenvironment will be started. This makes it really convenient and quick to use with a content management system like github


I hope this was helpful. It may look complicated but it’s very simple and i’ve just set it all up on a new computer in about 15 minutes using exactly these commands. Let me know if you have any issues.

**Comment by gdvallance** [comment]
@JMathiszig-Lee Thanks. I had not thought of using a bash shell under Windows. I am a Python novice, but not new to the commandline or Linux. :-)  The above looks straight-forward to me, although the Linux sub-system you refer to is NOT an option for me -- or at least there is no Linux sub-system option when I open the **turn windows features on and off** programme. IIRC it is a Windows 10 feature, and my NHS computer is Windows 7. 

However, the approach is one I will look at. I already have a bash shell through Git. Once upon a time I played with Babun and cygwin. I could reinstall one or other and try that if the Git bash shell does not work. For the Git bash hub the trick will be getting things to use Python 2.7 rather than Python 3.5 which is the default on my machine ...  

This said, a pure Windows implementation is probably still worth pursuing in the long run.

**Comment by davidmiller** [comment]
Hi @gdvallance interesting that you're looking to evaluate for a project at your department - did we discuss this in Oxford briefly?

I suspect we'd be more than happy to spend some time helping with the framework exploring / evaluating side of things either remotely or in person if we can find a good time & place to co-locate .

Feel free to drop me an email to david @ openhealthcare.org.uk if that's something that might work for you

**Comment by gdvallance** [comment]
@davidmiller thanks. Yes we did. I will be in touch. I am sure we can find a good time & place to co-locate ... v. keen to do this once I am a little more fluent in Django/Python dev. 

I *am* getting to grips with OPAL, but its slow due to other commitments/projects. FYI, to get operational ASAP I created an Ubuntu VM on my local Windows machine and have the bare-bones install working perfectly.

**Comment by davidmiller** [comment]
Hi @gdvallance 

Good to catch you last week at the interop summit - going to close this issue seeing as it seems you have a VM solution working !

Do get in touch if you have any further issues once you get back to looking at Opal 

Feel free to drop me a line on david@openhealthcare.org.uk if you have any questions et cetera :)
