### ISSUE TITLE
Scaffolding seems to be broken

### ISSUE THREAD

**Issue by JMathiszig-Lee** [openhealthcare/opal#923]
I tried the scaffolding function 

`opal scaffold anaesthetic
`
and get an error that seems to suggest requirment for django 1.7 is hardcoded somewhere

`The 'django-axes==1.7.0' distribution was not found and is required by opal`

**Comment by davidmiller** [comment]
Hi @JMathiszig-Lee that shouldn't happen - some kind of requirements confusion for sure...

Can you paste the output of 

`pip freeze` ?

**Comment by JMathiszig-Lee** [comment]
```
amqp==1.4.9
anyjson==0.3.3
billiard==3.3.0.23
celery==3.1.19
cffi==1.7.0
coverage==3.6
cryptography==1.4
dj-database-url==0.2.1
dj-static==0.0.6
Django==1.8.13
django-appconf==1.0.2
django-axes==1.7.0
django-celery==3.1.17
django-compressor==1.5
django-reversion==1.8.7
djangorestframework==3.2.2
enum34==1.1.6
ffs==0.0.8.1
gunicorn==0.17.4
idna==2.1
ipaddress==1.0.16
Jinja2==2.8
kombu==3.0.35
letter==0.4.1
MarkupSafe==0.23
-e git+https://github.com/openhealthcare/opal.git@6c20b7e98ba9088998133f80e9560365c8b9a9a2#egg=opal
psycopg2==2.5
pyasn1==0.1.9
pycparser==2.14
python-dateutil==2.4.2
pytz==2016.6.1
requests==2.7.0
six==1.10.0
static3==0.7.0
```

I was on django-axes 1.4 and Django 1.8.3 to start with. I upgrade Axes to the latest version but it still gave an error that resolved when i specified 1.7.0 and then it gave an error saying it needed Django 1.8.13

**Comment by davidmiller** [comment]
Opal seems pinned to [this specific commit](https://github.com/openhealthcare/opal/commit/6c20b7e98ba9088998133f80e9560365c8b9a9a2) which will cause problems sooner or later...

Is the master branch of https://github.com/anaesthetic-health-chart/anaesthetic up to date (e.g. what you're working from )?

**Comment by JMathiszig-Lee** [comment]
Nearly, just started a branch for the rapid turnover list form for which i was asking about the lookup lists. I'll commit and push it now

**Comment by davidmiller** [comment]
I believe that re-running `pip install -r requirements.txt` would have sorted out your dependencies.
You might like to do that anyway as it seems that the version of Opal you have in your virtualenv is pinned to that commit rather than the 0.8.0 branch which is what's in the requirements.txt (and probably more sensible for you).

If you're interested in the why: 

Opal declares a [setup.py](https://github.com/openhealthcare/opal/blob/v0.8.0/setup.py) which is used for Python packaging - it's the file that is read by pip when you run `pip install opal` to figure out what needs to happen. That file declares the other libraries we need to install.

Through a slightly circuitous route, the Opal command line tool installed with pip goes via that file and checks to see that the various dependencies are available.

(BTW I'm going to close this as not-a-bug in Opal per se but an issue with your virtualenv )
