### ISSUE TITLE
the metadata docs may need some work

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/opal#952]
User thought he needed to write a custom route provider, rather than the fact its often on the scope. 

Also didn't realise he needed to write in metadata.py. Docs maybe should be clearer, not sure how!

**Comment by davidmiller** [comment]
Right - I see how you could think that you need to add it to routes :(

@JMathiszig-Lee - IIRC this was related to https://github.com/anaesthetic-health-chart/anaesthetic/blob/master/anaesthetic/metadata.py ? 

Do you have a sense of how we might explain things better in https://github.com/openhealthcare/opal/blob/v0.8.2/doc/docs/guides/metadata.md  ?

**Comment by JMathiszig-Lee** [comment]
If this was me i think it was that i thought i had to create a pathway to feed the API with some new data from a form rather than use scope.editing.<MODEL NAME>

which is what we(well @fredkingham ) did here: 
https://github.com/anaesthetic-health-chart/anaesthetic/blob/master/anaesthetic/assets/js/anaesthetic/controllers/induction_drug_controller.js)
