### ISSUE TITLE
Add the translation to several languages

### ISSUE THREAD

**Issue by khchine5** [openhealthcare/opal#979]
It seems that Opal does not support translation to several languages.

**Comment by davidmiller** [comment]
Hi @khchine5 !

You're right - at the moment we're not set up for internationalization.

This is mostly a case of never having had anyone to translate Opal into another language !

Django has really pretty good support for i18n built in, and there is some tooling around it. The client side code might take some more thought, but is entirely tractable. (We've looked a little at https://angular-gettext.rocketeer.be/ before for instance.)

I suspect we'd be v. supportive of any attempt to move to a place where we support translations  - I'm guessing French would interest you based on your profile bio ? :)

**Comment by khchine5** [comment]
Hi @davidmiller ,

Yes, I am interesting to join  Opal teams' efforts and work on internationalization of the framework. French will be target language.

https://angular-gettext.rocketeer.be seems to be a good tools to use.

**Comment by davidmiller** [comment]
That sounds great !

We'd love to have some help in internationalizing the framework :) 

French is a super target language - particularly as I know enough FR to still understand text once it's translated (though not enough to attempt a translation myself sadly).

It's a few years since I last went through the process of internationalizing a codebase, but the next obvious steps might looks like

* Make sure that translation strings are all run through gettext 
* Extract the strings with `makemessages`

Then we're in a position to translate at least the strings that come from the Django side of things.

As I understand it [Transifex](http://transifex.com/) offers a free plan to Open Source projects, and people speak highly of it, so that's probably worth exploring.

What parts would you be most interested in helping with @khchine5 ?

**Comment by davidmiller** [comment]
No movement on this in > 18 months so closing.

We'd still welcome contributions, but unlikely to prioritise development towards translation from the core development team short-med term.
